# site settings
title: Proxima Symposium
subtitle: 2023
email: symposium@iniciativa-proxima.org
description: December 11-13, 2023<br /> Porto Alegre, RS, Brazil
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: 
state:
zip_code:
country:
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/iniciativaproxima/
  LinkedIn:
  Twitter: https://twitter.com/iniproxima
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from
  - jekyll-seo-tag